-- Generated-content ledger (dashboard rebuild, 2026-07-28).
-- One row per PIECE of content the platform generates (a whole carousel
-- = 1 row), written fire-and-forget at each generation site. This is the
-- only honest source for "content generated by platform + type" — chat
-- sessions (the old proxy) counted conversations, not content.
create table if not exists generated_content (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  platform text not null,            -- instagram | linkedin | x | facebook | tiktok | youtube | general
  content_type text not null,        -- text_post | image_post | carousel | story | reel | script | landing_page | newsletter | other
  source text,                       -- content-chat | ai-ceo | marketing-ai | plan-item | api
  session_id text,
  created_at timestamptz not null default now()
);
create index if not exists generated_content_user_created_idx on generated_content (user_id, created_at desc);
create index if not exists generated_content_user_platform_type_idx on generated_content (user_id, platform, content_type);

-- Applied together with the ledger (2026-07-28): stop stamping drafts as
-- published — every real publish path sets published_at explicitly.
alter table social_posts alter column published_at drop default;
