-- Placeholder for pre-existing migration 20260418025015 applied via raw SQL.
-- Schema is live on remote; this file exists so the CLI's local/remote
-- migration history sync check passes for new pushes.
